# Generated by Django 4.1.5 on 2023-01-25 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_newcontent_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(verbose_name='Номер карты')),
                ('cvv_kod', models.IntegerField(verbose_name='3 цифры')),
                ('date_of_kart', models.IntegerField(verbose_name='дата действия')),
                ('owner', models.CharField(max_length=50, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 16, 16, 4, 570095)),
        ),
    ]
