# Generated by Django 4.1.5 on 2023-01-27 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_payment_alter_newcontent_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 23, 35, 40, 99539)),
        ),
    ]
