# Generated by Django 4.1.5 on 2023-01-30 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_newcontent_date_of_publication_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('product', models.CharField(max_length=50, verbose_name='product')),
                ('id_product', models.IntegerField(verbose_name='id')),
            ],
            options={
                'verbose_name': 'basket',
                'verbose_name_plural': 'basket',
            },
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 21, 43, 59, 222997)),
        ),
    ]
