# Generated by Django 4.1.5 on 2023-02-15 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_user_basket_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcontent',
            name='count_viwes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 21, 3, 35, 32593)),
        ),
    ]
