# Generated by Django 4.1.5 on 2023-02-15 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_newcontent_count_viwes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 21, 5, 54, 44557)),
        ),
        migrations.CreateModel(
            name='PostCountViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesId', models.CharField(db_index=True, max_length=150)),
                ('postId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.newcontent')),
            ],
        ),
    ]
