# Generated by Django 4.1.5 on 2023-02-19 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_newcontent_date_of_publication_postcountviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 17, 29, 44, 335899)),
        ),
    ]
