# Generated by Django 4.1.5 on 2023-02-19 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productview_delete_pageview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontent',
            name='date_of_publication',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 21, 23, 46, 937991)),
        ),
        migrations.DeleteModel(
            name='PostCountViews',
        ),
    ]
